name: habit_tracker
description: Habit Tracker App — ceklis kebiasaan harian
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP requests
  http: ^1.2.1

  # State management
  provider: ^6.1.2

  # Local storage (token, user data)
  shared_preferences: ^2.2.3

  # UI
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  fl_chart: ^0.68.0
  percent_indicator: ^4.2.3

  # Form & validasi
  flutter_form_builder: ^9.3.0

  # Lain-lain
  intl: ^0.19.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/